var date = new Date();
console.log(date);

var friendsAge = [13, 20, 25,26,29];
var mithuAge = friendsAge[1];
friendsAge[2] = 22;
console.log(mithuAge);
console.log(friendsAge);
var position = friendsAge.indexOf(26);
console.log(position);
position = friendsAge.indexOf(124);
console.log(position);
friendsAge.push(15);
console.log(friendsAge);
console.log(friendsAge.length);
friendsAge.pop();
console.log(friendsAge);
friendsAge.unshift(12, 14);
console.log(friendsAge);
friendsAge.shift();
console.log(friendsAge);